on:
  [push, workflow_dispatch]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3 
        with:
          node-version: 18
      - run: npm i
      - run: npm run lint

  clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
      - run: cmake libs/
      - run: clang-tidy -p . libs/src/* --header-filter=libs/src/*.h
      - run: clang-format libs/src/* --dry-run -Werror

