run-name: "Checks linting, builds and runs tests"
on:
  [push, workflow_dispatch]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3 
        with:
          node-version: 18
      - run: npm i
      - run: npm run lint

  clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
      - run: cd backend_test
      - run: emcmake cmake .
      - run: clang-tidy -p . ../src/cpp/* --header-filter=../src/cpp/*.h --use-color
      - run: clang-format ../src/cpp/* --dry-run -Werror

